version: "3"
services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      TZ: America/Chicago
      WATCHTOWER_SCHEDULE: 0 0 3 * * *
      WATCHTOWER_DEBUG: "true"
