version: "3.3"

services:
  
  youtrack:
    image: jetbrains/youtrack:2024.2.37269
    container_name: "youtrack"
    volumes:
      - /home/adam/docker/volumes/youtrack/data:/opt/youtrack/data
      - /home/adam/docker/volumes/youtrack/conf:/opt/youtrack/conf
      - /home/adam/docker/volumes/youtrack/logs:/opt/youtrack/logs
      - /home/adam/docker/volumes/youtrack/backups:/opt/youtrack/backups

# Set directory permissions https://www.jetbrains.com/help/youtrack/server/youtrack-docker-installation.html#create-and-configure-directories
